ALPHABET_NUM = 26
ORD_A = ord('A')

# Enigma I (1930)
M3I = "EKMFLGDQVZNTOWYHXUSPAIBRCJ"
# Enigma I (1930)
M3II = "AJDKSIRUXBLHWTMCQGZNPYFVOE"
# Enigma I (1930)
M3III = "BDFHJLCPRTXVZNYEIWGAKMUSQO"
# M3 Army (1938)
M3IV = "ESOVPZJAYQUIRHXLNFTGKDCMWB"
# M3 Army (1938)
M3V = "VZBRGITYUPSDNHLXAWMJQOFECK"
# M3 Naval (1939)
M3VI = "JPGVOUMFYQBENHZRDKASXLICTW"
# M3 Naval (1939)
M3VII = "NZJHGRCXMYSWBOUFAIVLPEKQDT"
# M3 Naval (1939)
M3VIII = "FKQHTLXOCBJSPDZRAMEWNIUYGV"

M3_B_REFLECTOR = "YRUHQSLDPXNGOKMIEBFZCWVJAT"
M3_A_REFLECTOR = "EJMZALYXVBWFCRQUONTSPIKHGD"
M3_C_REFLECTOR = "FVPJIAOYEDRZXWGCTKUQSBNMHL"


def ltoi(letter) -> int:
    return ord(letter.upper()) - ORD_A


def itol(i) -> str:
    return chr((i % ALPHABET_NUM) + ORD_A)
