ALPHABET_NUM = 26
ORD_A = ord('A')
ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
MAX_LABEL_LENGTH = 81

# Enigma I (1930)
EnigmaI = ["EKMFLGDQVZNTOWYHXUSPAIBRCJ", "Q"]
# Enigma I (1930)
EnigmaII = ["AJDKSIRUXBLHWTMCQGZNPYFVOE", "E"]
# Enigma I (1930)
EnigmaIII = ["BDFHJLCPRTXVZNYEIWGAKMUSQO", "V"]
# M3 Army (1938)
M3IV = ["ESOVPZJAYQUIRHXLNFTGKDCMWB", "J"]
# M3 Army (1938)
M3V = ["VZBRGITYUPSDNHLXAWMJQOFECK", "Z"]
# M3 Naval (1939)
M3VI = ["JPGVOUMFYQBENHZRDKASXLICTW", "ZM"]
# M3 Naval (1939)
M3VII = ["NZJHGRCXMYSWBOUFAIVLPEKQDT", "ZM"]
# M3 Naval (1939)
M3VIII = ["FKQHTLXOCBJSPDZRAMEWNIUYGV", "ZM"]

B_REFLECTOR = "YRUHQSLDPXNGOKMIEBFZCWVJAT"
A_REFLECTOR = "EJMZALYXVBWFCRQUONTSPIKHGD"
C_REFLECTOR = "FVPJIAOYEDRZXWGCTKUQSBNMHL"

KEYBOARD_LAYOUT = [
    list("QWERTZUIO"),
    list("ASDFGHJK"),
    list("PYXCVBNML")
]


def ltoi(letter) -> int:
    return ord(letter.upper()) - ORD_A


def itol(i) -> str:
    return chr((i % ALPHABET_NUM) + ORD_A)


def safe_truncate(text, max_length=MAX_LABEL_LENGTH):
    if len(text) > max_length:
        return text[:max_length] + "..."
    return text
